#!/bin/sh

if [ $# != 1 ]; then
    echo "Usage: tools/flash [example name]"
    echo "This will flash [example name].elf onto the device after converting to a hex file."
    exit 1
fi
name=$1
cd build/examples
if [ ! -e $name.elf ]; then
    echo "File $name.elf couldn't be found"
    exit 1
fi

avr-objcopy -j .text -j .data -O ihex $name.elf $name.hex
avr-size --format=avr --mcu=m328p $name.elf
# avrdude -c arduino -P /dev/ttyACM0 -p m328p -U flash:w:$name.hex:i
avrdude -c usbtiny -p m328p -U flash:w:$name.hex:i
